git:
  overrideGpg: true
  pagers:
    - pager: zsh -c "delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format=\"lazygit-edit://{path}:{line}\" \$( [ \"\$(defaults read -g AppleInterfaceStyle 2>&1)\" = \"Dark\" ] && echo \"--dark\" || echo \"--light\" )"
